\getenv app_password DATABASE_PASSWORD
CREATE ROLE cria LOGIN PASSWORD :'app_password' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE SCHEMA app AUTHORIZATION cria;
GRANT CONNECT ON DATABASE moovit TO cria;
ALTER ROLE cria SET search_path=app;
