<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../Cria.Application/Cria.Application.csproj" /><PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" /><PackageReference Include="Npgsql" Version="10.0.3" /><FrameworkReference Include="Microsoft.AspNetCore.App" /></ItemGroup><ItemGroup><EmbeddedResource Include="Data/metro.json" /><EmbeddedResource Include="Data/places.json" /><EmbeddedResource Include="Data/accounts-v1.sql" /></ItemGroup></Project>
