<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../Cria.Application/Cria.Application.csproj" /><PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" /><FrameworkReference Include="Microsoft.AspNetCore.App" /></ItemGroup><ItemGroup><EmbeddedResource Include="Data/metro.json" /></ItemGroup></Project>
